services:
  counter:
    build: .
    container_name: counter
    ports:
    - '8082:8082'
    networks:
      - projectsbcxp_my_external_network
networks:
  projectsbcxp_my_external_network :
    external: true
