services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projects'
      - 'POSTGRES_USER=project'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - './src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql'
    restart: 'always'
    networks:
      - 'my_external_network'

  backend:
    build: .
    container_name: backend
    ports:
      - '8081:8081'
    depends_on:
      - 'postgres'
    networks:
      - 'my_external_network'

networks:
  my_external_network:
    driver: bridge


  #nginx:
   # container_name: projects-frontend
   # build: nginx/
  # ports:
   #   - "8088:80"
   # extra_hosts:
   #  - "host.docker.internal:host-gateway"